# Generated by Django 3.0.3 on 2025-11-17 00:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100, verbose_name='ラベル名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'ラベル',
                'verbose_name_plural': 'ラベル',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='テーマ名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'テーマ',
                'verbose_name_plural': 'テーマ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'gif'])], verbose_name='画像')),
                ('split', models.CharField(blank=True, choices=[('train', 'Train'), ('valid', 'Valid'), ('test', 'Test')], max_length=10, null=True, verbose_name='データ分割')),
                ('labeled_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ラベル付けした人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.Label', verbose_name='ラベル')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.Theme', verbose_name='テーマ')),
            ],
            options={
                'verbose_name': '学習データ',
                'verbose_name_plural': '学習データ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlflow_run_id', models.CharField(max_length=200, unique=True, verbose_name='MLflow Run ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='data_management.Theme', verbose_name='テーマ')),
            ],
            options={
                'verbose_name': 'モデル',
                'verbose_name_plural': 'モデル',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='label',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='data_management.Theme', verbose_name='テーマ'),
        ),
        migrations.CreateModel(
            name='ModelTrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_data_relations', to='data_management.Model', verbose_name='モデル')),
                ('train_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_relations', to='data_management.TrainData', verbose_name='学習データ')),
            ],
            options={
                'verbose_name': 'モデル-学習データ関連',
                'verbose_name_plural': 'モデル-学習データ関連',
                'unique_together': {('model', 'train_data')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('theme', 'label_name')},
        ),
    ]
