# Generated by Django 3.0.3 on 2025-11-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traindata', to='data_management.Theme', verbose_name='テーマ'),
        ),
    ]
