# Generated by Django 3.0.3 on 2025-11-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_auto_20251117_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='best_score',
            field=models.FloatField(blank=True, null=True, verbose_name='最良スコア'),
        ),
        migrations.AddField(
            model_name='model',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='model',
            name='status',
            field=models.CharField(choices=[('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='model',
            name='training_params',
            field=models.TextField(blank=True, null=True, verbose_name='学習パラメータ（JSON）'),
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField(blank=True, null=True, verbose_name='プロセスID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='ステータス')),
                ('log_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='ログファイルパス')),
                ('params_yaml', models.TextField(blank=True, null=True, verbose_name='params.yaml')),
                ('optuna_params_yaml', models.TextField(blank=True, null=True, verbose_name='optuna_params.yaml')),
                ('auguments_yaml', models.TextField(blank=True, null=True, verbose_name='auguments.yaml')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='作成者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='data_management.Model', verbose_name='モデル')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='data_management.Theme', verbose_name='テーマ')),
            ],
            options={
                'verbose_name': '学習ジョブ',
                'verbose_name_plural': '学習ジョブ',
                'ordering': ['-created_at'],
            },
        ),
    ]
