# Generated by Django 3.0.3 on 2025-11-17 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_auto_20251117_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltraindata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AddField(
            model_name='modeltraindata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
